namespace CraftoraApi.DTOs.Media;

public sealed record MediaResponseDto(
    Guid Id,
    Guid ShopId,
    string ShopName,
    string ShopSlug,
    string? ShopLogoUrl,
    string? ShopLogoPublicUrl,
    bool IsShopVerified,
    Guid? ProductId,
    string? ProductTitle,
    string? ProductType,
    string? ProductCoverImagePublicUrl,
    string VideoUrl,
    string? VideoPublicUrl,
    string? ThumbnailUrl,
    string? ThumbnailPublicUrl,
    string? Caption,
    List<string> Hashtags,
    int ViewCount,
    int LikeCount,
    int CommentCount,
    int SaveCount,
    int ShareCount,
    string Status,
    DateTime? CreatedAt,
    bool IsLiked = false,
    bool IsSaved = false);
